### ISSUE TITLE
Add: latest talks in the context of vertex fitting and jet algorithm guidance 

### ISSUE THREAD

**Issue by amanmdesai** [HEP-FCC/FCCeePhysicsPerformance#45]
Hi, 

I think it would be useful to add the following talks to the [README.md](https://github.com/HEP-FCC/FCCeePhysicsPerformance/blob/master/General/README.md)

Vertex fitting update:
https://indico.cern.ch/event/1180976/contributions/4960968/attachments/2481467/4259924/Bedeschi_Vertexing_Jul2022.pdf

Basic guidance on jet algorithms:
https://indico.cern.ch/event/1173562/contributions/4929025/attachments/2470068/4237859/2022-06-FCC-jets.pdf

**Comment by EmanuelPerez** [comment]
Hi Aman,

Gavin's talk on jets is linked already.

I can add the Franco's talk on vertexing updates indeed. Some more extended tutorial of
vertexing in fccanalyses will be provided soon.

Cheers,

E.


On 28 Jul 2022, at 09:57, Aman Desai ***@***.******@***.***>> wrote:



Hi,

I think it would be nice to the following talks to the README.md<https://github.com/HEP-FCC/FCCeePhysicsPerformance/blob/master/General/README.md>

Vertex fitting update:
https://indico.cern.ch/event/1180976/contributions/4960968/attachments/2481467/4259924/Bedeschi_Vertexing_Jul2022.pdf

Basic guidance on jet algorithms:
https://indico.cern.ch/event/1173562/contributions/4929025/attachments/2470068/4237859/2022-06-FCC-jets.pdf

**Comment by amanmdesai** [comment]
Thanks for the reply. 
Yes Prof. Gavin's talk is already linked (I missed it somehow.) 

The extended tutorial on vertexing would be great. Thanks.
